"""Add date_liked column to Like table

Revision ID: 489b01e864c2
Revises: 0a8307a402f0
Create Date: 2024-07-05 00:25:16.970377

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '489b01e864c2'
down_revision = '0a8307a402f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_liked', sa.DateTime(), nullable=False))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('total_transactions',
               existing_type=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('total_transactions',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('balance',
               existing_type=mysql.FLOAT(),
               nullable=True)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               nullable=True)

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_column('date_liked')

    # ### end Alembic commands ###
