"""empty message

Revision ID: 92536d5da886
Revises: 83682b31cc67
Create Date: 2024-06-30 19:31:06.842058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92536d5da886'
down_revision = '83682b31cc67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_transactions', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('total_transactions')

    # ### end Alembic commands ###
