"""empty message

Revision ID: ac5f2428cc53
Revises: 3b67dc041e19
Create Date: 2024-07-01 23:46:09.822757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5f2428cc53'
down_revision = '3b67dc041e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('comment_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'comment', ['parent_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_ibfk_2', 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key('comment_ibfk_1', 'comment', ['parent_id'], ['id'])

    # ### end Alembic commands ###
