"""empty message

Revision ID: b3159792e84d
Revises: b6dd8cd4240e
Create Date: 2024-04-26 21:07:20.234484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3159792e84d'
down_revision = 'b6dd8cd4240e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cat_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'categorie', ['cat_id'], ['id_cat'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cat_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
