"""empty message

Revision ID: f8123e6b5d67
Revises: 197765150187
Create Date: 2024-07-02 00:21:36.355373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8123e6b5d67'
down_revision = '197765150187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_ibfk_5', type_='foreignkey')
        batch_op.drop_constraint('comment_ibfk_4', type_='foreignkey')
        batch_op.create_foreign_key(None, 'comment', ['parent_id'], ['id'])
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_ibfk_4', 'comment', ['parent_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('comment_ibfk_5', 'post', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
